name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 5 * * 2"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  # push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          template: classic
          # Core
          base: header
          config_octicon: yes
          config_timezone: Europe/Lisbon
          ######################
          # Gists
          ######################
          plugin_gists: yes
          ######################
          # Notable contributions
          ######################
          plugin_notable: no ###
          plugin_notable_indepth: yes
          plugin_notable_from: organization # | user | all
          plugin_notable_repositories: no
          plugin_notable_types: commit, issue, pull_request
          ######################
          # Languages activity
          ######################
          plugin_languages: yes
          plugin_languages_other: yes
          plugin_languages_indepth: yes
          plugin_languages_indepth_custom: pineman/abra, pineman/fpt
          plugin_languages_sections: most-used  # recently-used
          # plugin_languages_recent_days: 360
          # plugin_languages_recent_load: 900 # [0, 1000]
          plugin_languages_details: lines, percentage
          plugin_languages_categories: programming
          plugin_languages_ignored: renderscript, html, css, json, toml, yaml, xml, godot resource
          ######################
          # Random code snippet
          ######################
          plugin_code: no ######
          plugin_code_days: 360
          plugin_code_load: 900
          # https://github.com/lowlighter/metrics/blob/master/source/plugins/code/index.mjs#L59-L62
          # https://sourcegraph.com/npm/linguist-js/-/blob/ext/languages.yml
          # comma-separated, .toLocaleLowerCase()
          # webassembly?
          plugin_code_languages: c, c#, c++, java, javascript, powershell, python, ruby, rust, shell, lua, typescript, actionscript, autohotkey, assembly, angelscript, awk, apl, cmake, clips, pony, haskell, f#, fish, forth, elm, emacs lisp, nix, nushell, game maker language, gdscript, go, gleam, groovy, glsl, jq, ocaml, raku, scala, svelte, tex, ti program, dogescript, sql, vba, vbscript, vim script, vue, zig
          # consider plugin_languages_aliases: javascript:JS, typescript:TS, etc.
