name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 5 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          template: classic
          # Core
          base: header
          config_octicon: yes
          config_timezone: Europe/Lisbon
          # Gists
          plugin_gists: yes
          # Notable contributions
          plugin_notable: yes
          plugin_notable_indepth: yes
          plugin_notable_from: all
          plugin_notable_repositories: yes
          plugin_notable_types: "commit,issue,pull_request"
          # Projects
          plugin_projects: yes
          plugin_projects_repositories: pineman/fpt/projects/1
          plugin_projects_descriptions: yes
